console.log(typeof "Hossam Shiref");
console.log(typeof 500);
console.log(typeof 600.6);
console.log(typeof true);
console.log(typeof false);
console.log(typeof [10, 20, 30]);
console.log(typeof ["hossam", "shiref", "ahmed"]);
console.log(typeof { name: "Hossam", age: 15, state: true });
console.log(typeof undefined);
console.log(typeof null);
